name: publish

on: [push]

jobs:
  publish-dbt-docker-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update credentials in profiles.yml
      run: |-
        sed -i "s/ENV/${{secrets.ENV}}/g" "dbt_profiles.yml"
        sed -i "s/DATABRICKS_HOST_URL/${{secrets.DATABRICKS_HOST_URL}}/g" "dbt_profiles.yml"
        sed -i "s/DATABRICKS_HTTP_PATH/${{secrets.DATABRICKS_HTTP_PATH}}/g" "dbt_profiles.yml"
        sed -i "s/DATABRICKS_ACCESS_TOKEN/${{secrets.DATABRICKS_ACCESS_TOKEN}}/g" "dbt_profiles.yml"

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT_TOKEN }}

    - name: Build the databricks-dbt Docker image
      run: |
        docker build . --tag ghcr.io/hopin-team/databricks-dbt:latest
        docker run ghcr.io/hopin-team/databricks-dbt:latest
        docker push ghcr.io/hopin-team/databricks-dbt:latest
