name: publish

on: [push]

jobs:
  publish-dbt-docker-image:
    runs-on: ubuntu-latest
    environment: stage

    steps:
    - uses: actions/checkout@v2

#    - uses: microsoft/variable-substitution@v1
#        with:
#          files: 'dbt_profiles.yml'
#        env:
#          ENV: ${{secrets.ENV}}
#          DATABRICKS_HOST_URL: ${{secrets.DATABRICKS_HOST_URL}}
#          DATABRICKS_HTTP_PATH: ${{secrets.DATABRICKS_HTTP_PATH}}
#          DATABRICKS_ACCESS_TOKEN: ${{secrets.DATABRICKS_ACCESS_TOKEN}}

    - name: Update credentials in profiles.yml
      env:
        ENV: ${{secrets.ENV}}
        DATABRICKS_HOST_URL: ${{secrets.DATABRICKS_HOST_URL}}
        DATABRICKS_HTTP_PATH: ${{secrets.DATABRICKS_HTTP_PATH}}
        DATABRICKS_ACCESS_TOKEN: ${{secrets.DATABRICKS_ACCESS_TOKEN}}
      run: |
        echo $ENV
        sed -i -e "s/ENV/$ENV/g" dbt_profiles.yml
        sed -i -e "s/DATABRICKS_HOST_URL/$DATABRICKS_HOST_URL/g" dbt_profiles.yml
        sed -i -e "s/DATABRICKS_HTTP_PATH/$DATABRICKS_HTTP_PATH/g" dbt_profiles.yml
        sed -i -e "s/DATABRICKS_ACCESS_TOKEN/$DATABRICKS_ACCESS_TOKEN/g" dbt_profiles.yml

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT_TOKEN }}

    - name: Build the databricks-dbt Docker image
      run: |
        docker build . --tag ghcr.io/hopin-team/databricks-dbt:latest
        docker run ghcr.io/hopin-team/databricks-dbt:latest
        docker push ghcr.io/hopin-team/databricks-dbt:latest
