name: dbt-cron-jobs

on:
  schedule:
    - cron: '@hourly'
    - cron: '30 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hopin-team/databricks-dbt:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PAT_TOKEN }}
    environment: stage

    steps:
      - name: Running Zendesk Hopin
        if: github.event.schedule = '@hourly'
        run: dbt run --target zendesk_hopin --vars "{'zendesk_database':'zendesk', 'zendesk_schema':'zendesk'}"
      - name: Running Zendesk Streamyard
        if: github.event.schedule = '30 10 * * *'
        run: dbt run --target zendesk_streamyard --vars "{'zendesk_database':'zendesk_streamyard', 'zendesk_schema':'zendesk_streamyard'}"
