name: dbt-cron-jobs

on:
  schedule:
    - cron: "0 10 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hopin-team/databricks-dbt:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PAT_TOKEN }}
    environment: production

    steps:
      - name: Running Zendesk Hopin
        run: |
          dbt run --target zendesk_hopin --vars "{'zendesk_database':'zendesk', 'zendesk_schema':'zendesk'}"
