name: dbt-cron-jobs

#on:
#  schedule:
#    - cron: '0 10 * * *'
#    - cron: '30 10 * * *'

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hopin-team/databricks-dbt:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PAT_TOKEN }}
    environment: production

    steps:
#      - name: Running Zendesk Hopin
#        if: github.event.schedule == '0 10 * * *'
#        run: |
#          cd /dbt/dbt_zendesk
#          dbt run --target zendesk_hopin --vars "{'zendesk_schema':'zendesk'}"
#      - name: Running Zendesk Streamyard
#        if: github.event.schedule == '30 10 * * *'
#        run: |
#          cd /dbt/dbt_zendesk
#          dbt run --target zendesk_streamyard --vars "{'zendesk_schema':'zendesk_streamyard'}"
      - name: test dbt run
        run: |
          cd /dbt/dbt_zendesk
          cat ~/.dbt/profiles.yml
          dbt run --target zendesk_hopin --vars "{'zendesk_schema':'zendesk'}"
